apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "hello"
  labels:
    appName: "hello"
spec:
  replicas: 3
  selector:
    matchLabels:
      appName: "hello"

  #update
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        appName: "hello"
    spec:
      restartPolicy: Always
      containers:
        - name: hello
          image: "hello-impl:1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: "/status/ready"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 180
          livenessProbe:
            httpGet:
              path: "/status/alive"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 120
          env:
            - name: "APPLICATION_SECRET"
              # change this to your own unique secret
              value: "M5T/zBAqxiOcmHR1Ak2xjUNKvomQV6eD1XUTpvPpNkI="
            - name: "JAVA_OPTS"
              value: "-Xms128m -Xmx256m -Dconfig.resource=prod-application.conf -DCASSANDRA_SERVICE_NAME=_cql._tcp.reactive-sandbox-cassandra.default.svc.cluster.local -DKAFKA_SERVICE_NAME=_broker._tcp.reactive-sandbox-kafka.default.svc.cluster.local -Dplay.http.secret.key=$(APPLICATION_SECRET)"
          ports:
            - containerPort: 9000
              name: http
            - containerPort: 2552
              name: remoting
            - containerPort: 8558
              name: management
          volumeMounts: []

          resources:
            limits:
              cpu: 0.15
              memory: 512Mi
            requests:
              cpu: 0.15
              memory: 512Mi
      volumes: []

---
#headless
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: "hello"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: "hello-internal"
spec:
  ports:
  - name: management
    port: 8558
    protocol: TCP
    targetPort: 8558
  - name: remoting
    port: 2552
    protocol: TCP
    targetPort: 2552
  selector:
    appName: "hello"
  clusterIP: None
  publishNotReadyAddresses: true
#headless
---

apiVersion: v1
kind: Service
metadata:
  labels:
    appName: hello
  name: hello
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    appName: hello
  type: LoadBalancer
